// internal/kernel/apperr/catalog.go
package apperr

type ErrorKind string

const (
	//AUTHENTICATION
	AUTH_REQUIRED      ErrorKind = "AUTH_REQUIRED"
	AUTH_TOKEN_INVALID ErrorKind = "AUTH_TOKEN_INVALID"
	AUTH_TOKEN_EXPIRED ErrorKind = "AUTH_TOKEN_EXPIRED"
	//ACCESS AND PERMISSIONS
	PROFILE_NOT_FOUND   ErrorKind = "PROFILE_NOT_FOUND"
	ACCESS_DENIED       ErrorKind = "ACCESS_DENIED"
	ACTION_NOT_ALLOWED  ErrorKind = "ACTION_NOT_ALLOWED"
	ONBOARDING_REQUIRED ErrorKind = "ONBOARDING_REQUIRED"
	ACCOUNT_DEACTIVATED ErrorKind = "ACCOUNT_DEACTIVATED"
	//VALIDATION
	VALIDATION_FAILED      ErrorKind = "VALIDATION_FAILED"
	REQUIRED_FIELD_MISSING ErrorKind = "REQUIRED_FIELD_MISSING"
	INVALID_FIELD_FORMAT   ErrorKind = "INVALID_FIELD_FORMAT"
	INVALID_ENUM_VALUE     ErrorKind = "INVALID_ENUM_VALUE"
	INVALID_DATE           ErrorKind = "INVALID_DATE"
	//NOT FOUND (DEPOIS PODEM EXISTIR NOT_FOUND ESPECÍFICOS)
	NOT_FOUND ErrorKind = "NOT_FOUND"
	//CONFLICT
	RESOURCE_CONFLICT       ErrorKind = "RESOURCE_CONFLICT"
	RESOURCE_ALREADY_EXISTS ErrorKind = "RESOURCE_ALREADY_EXISTS"
	//DOMAIN
	DOMAIN_RULE_VIOLATION ErrorKind = "DOMAIN_RULE_VIOLATION"
	//INFRA
	INFRA_AUTHENTICATION_ERROR   ErrorKind = "INFRA_AUTHENTICATION_ERROR"
	INFRA_DATABASE_ERROR         ErrorKind = "INFRA_DATABASE_ERROR"
	INFRA_STORAGE_ERROR          ErrorKind = "INFRA_STORAGE_ERROR"
	INFRA_EXTERNAL_SERVICE_ERROR ErrorKind = "INFRA_EXTERNAL_SERVICE_ERROR"
	INFRA_TIMEOUT                ErrorKind = "INFRA_TIMEOUT"
	//LLIMITER
	RATE_LIMIT_EXCEEDED  ErrorKind = "RATE_LIMIT_EXCEEDED"
	UPLOAD_SIZE_EXCEEDED ErrorKind = "UPLOAD_SIZE_EXCEEDED"
	//INTERNAL
	INTERNAL_ERROR ErrorKind = "INTERNAL_ERROR"
)
